// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/richard/Documents/work/G2/site/node_modules/@antv/dumi-theme-antv/dist/slots/ExampleSider/index.js';
