// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/richard/Documents/work/G2/site/node_modules/.pnpm/dumi@2.4.17_@babel+core@7.28.0_@swc+helpers@0.5.1_@types+node@24.1.0_@types+react@19.1._ebae42d2791f93a51895ccc3fa68101f/node_modules/dumi/theme-default/slots/RtlSwitch/index.js';
